---
#! ******************************************
#! Secrets you will need to run this pipeline
#! ******************************************
github_token: &github_token ((cve_scan.github_access_token))
  #! github_token is needed so the pipeline can access the tas-cve cli for uploading to dependency-track. We recommend generating from your team github account. You'll want to use any token that can access your github release.
github_key: &github_key ((cve_scan.private_key))
  #! github_key is needed so the pipeline can clone the git repos for the tasks needed and the repo to be scanned.  We recommend generating from your team github account. If you want to run tasks directly from this repo, contact @ryanhall to ask for creds.
#! **************
#! End of secrets
#! **************

resources:
  - name: concourse-cve-scan
    type: git
    source:
      uri: git@github.com:cloudfoundry-incubator/concourse-cve-scan.git
      branch: main
      private_key: *github_key
  - name: bosh-release-repo
    type: git
    source:
      uri: git@github.com:cloudfoundry/cf-networking-release.git
      branch: develop
      private_key: *github_key
jobs:
  - name: scan-for-cves
    plan:
      - in_parallel:
          - get: concourse-cve-scan
          - get: bosh-release-repo
      - task: scan-with-syft-and-grype
        file: concourse-cve-scan/tasks/scan-for-cves/scan-for-cves.yml
        params:
          GRYPE_FAILURE_LEVEL: 